# Site Info
title: 菡萏
url: http://youhandan.github.io
logo: '/img/system/logo.png'

# Site configurations
gems:
  - jekyll-paginate
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
excerpt_separator: "<!-- more -->"
sass:
  sass_dir: /_scss
  style: compressed
paginate: 10
paginate_path: "/blog/page:num"
permalink: pretty

# Comment setting
comments :
  provider : duoshuo
  duoshuo :
    short_name : youhandan
