# Site Info
title: 菡萏
url: http://youhandan.github.io
logo: '/img/logo.png'

# Site configurations
markdown: kramdown
sass:
  sass_dir: /_scss
  style: compressed
permalink: /blog/:year/:month/:day/:title