# Site Info
title: 菡萏
url: http://youhandan.github.io
logo: '/img/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  sass_dir: /_scss
  style: compressed
paginate: 2
paginate_path: "/blog/page:num"
permalink: pretty

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

# Comment setting
comments :
  provider : duoshuo
  duoshuo :
    short_name : youhandan //替换为你刚刚注册的短名
