# Site Info
title: 菡萏
url: http://youhandan.github.io
logo: '/img/logo.png'

# Site configurations
markdown: kramdown
sass:
  sass_dir: /_scss
  style: compressed
permalink: /blog/:year/:month/:day/:title
# Comment setting
comments :
  provider : duoshuo
  duoshuo :
    short_name : youhandan //替换为你刚刚注册的短名
